apiVersion: garden.io/v1
kind: Project
name: pulumi
variables:
   pulumiAppOrg: srihas3 # <--- replace with your own org name
environments:
  - name: local
providers:
  - name: pulumi
    environments: [local]
    orgName: ${var.pulumiAppOrg}
    version: 3.40.0 # <--- currently pinned to older version because of https://github.com/pulumi/pulumi/issues/11444
