apiVersion: garden.io/v1
kind: Project
name: pulumi
variables:
   pulumiAppOrg: garden # <--- replace with your own org name
environments:
  - name: local
providers:
  - name: pulumi
    environments: [local]
    orgName: ${var.pulumiAppOrg}
