apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "registry-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "registry-proxy.name" . }}
    helm.sh/chart: {{ include "registry-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "registry-proxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 80%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "registry-proxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: envoyproxy/envoy-alpine:v1.11.0
          imagePullPolicy: IfNotPresent
          command: ["envoy"]
          args: ["-c", "/etc/envoy.yaml", "--service-cluster", "$(POD_NAME)"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: envoy-yaml
              mountPath: /etc/envoy.yaml
              subPath: envoy.yaml
          ports:
            - name: docker
              containerPort: 5000
              hostPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: envoy-yaml
          configMap:
            name: {{ include "registry-proxy.fullname" . }}-envoy
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
