apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "registry-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "registry-proxy.name" . }}
    helm.sh/chart: {{ include "registry-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "registry-proxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 80%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "registry-proxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              # (Roughly) figure out the CIDR range in the cluster. This is important because we don't want to allow
              # public connections here, in case there's no firewall in front of the cluster to block external access
              # to the hostPort.
              export CIDR_RANGE=$(echo $KUBERNETES_SERVICE_HOST | cut -d '.' -f 1).0.0.0/8
              # Proxy node connections on 127.0.0.1:5000 to the docker registry
              socat -d TCP-LISTEN:5000,fork,range=$CIDR_RANGE TCP:{{ .Values.registry.hostname }}:5000
          ports:
            - name: docker
              containerPort: 5000
              hostPort: 5000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
