kind: Module
type: helm
name: registry-proxy
description: DaemonSet that proxies connections to the docker registry service on each node
releaseName: garden-registry-proxy
values:
  dockerDaemon:
    registry:
      hostname: ${var.registry-hostname || "foo"}
      # tlsSecretName: ${variables.registry-tls-secret-name}
