apiVersion: garden.io/v1
kind: Project
name: ephemeral-cluster-demo
environments:
  - name: remote
providers:
  - name: garden-kubernetes
    environments: [remote]
variables:
  userId: ${kebabCase(local.username)}

