apiVersion: garden.io/v1
kind: Project
name: vote
environments:
  - name: local
    variables:
      baseHostname: vote.local.demo.garden
  - name: remote
    variables:
      baseHostname: ${project.name}-testing-${var.userId}.dev-1.sys.garden
providers:
  - name: octant
  - name: local-kubernetes
    environments: [local]
  - name: kubernetes
    environments: [remote]
    # Replace the below values as appropriate
    context: arn:aws:eks:eu-central-1:873483817304:cluster/garden-ci-k8s-cfb88b38
    buildMode: kaniko
    imagePullSecrets:
      - name: regcred
        namespace: default
    deploymentRegistry:
      hostname: 873483817304.dkr.ecr.eu-central-1.amazonaws.com
      namespace: vote-demo
variables:
  userId: ${kebabCase(local.username)}
  postgres-database: postgres
  # Only use for testing!
  postgres-username: postgres
  postgres-password: test-password
