# Default values for garden-registry-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: envoyproxy/envoy-alpine
  tag: v1.11.0
  pullPolicy: IfNotPresent

nameOverride: garden-registry-proxy
fullnameOverride: garden-registry-proxy

registry:
  hostname: garden-docker-registry
  tlsSecretName: garden-docker-registry-tls

nodeSelector: {}

tolerations: []

affinity: {}
