# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: sudo apt install rsync ruby ruby-dev cmake libicu-dev pkg-config
      - run: sudo gem install --no-document copyright-header
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

      # a couple of special cases needed just for local builds
      - run: |
          if [[ $CIRCLE_SHELL_ENV == *"localbuild"* ]]; then
            sudo chown $(whoami): /var/run/docker.sock
            npm rebuild
          fi

      # run tests
      - run: npm test
      - run: ./bin/integ
