require: build/test/setup.js
watch-files:
  - build/**/*
ignore:
  - build/test/e2e/**/*
  - build/test/integ/**/*
  - test/,src/,.garden
reporter: xunit
reporter-option:
  - "output=~/test-results/core-unit/results.xml"
timeout: 30000
exit: true
spec:
  - build/test/unit/**/*.js
