require: build/test/setup.js
watch-files:
  - build/**/*
ignore:
  - build/test/unit/**/*
  - build/test/e2e/**/*
  - test/,src/,.garden
reporter: mocha-junit-reporter
reporter-option:
  - mochaFile=../test-results/core-integ/test-results.xml
timeout: 50000
exit: true
spec:
  - build/test/integ/**/*.js
