require: build/test/setup.js
watch-files:
  - build/**/*
ignore:
  - build/test/e2e/**/*
  - build/test/integ/**/*
  - test/,src/,.garden
reporter: mocha-junit-reporter
reporter-option:
  - mochaFile=../test-results/core-unit/test-results.xml
timeout: 30000
exit: true
spec:
  - build/test/unit/**/*.js
