require: build/test/setup.js
watch-files:
  - build/**/*
ignore:
  - build/test/unit/**/*
  - build/test/e2e/**/*
  - test/,src/,.garden
reporter: xunit
reporter-option:
  - output=../test-results/core-integ/results.xml
timeout: 50000
exit: true
spec:
  - build/test/integ/**/*.js
