extensions:
  memory_ballast:
    size_mib: 512

receivers:
  otlp:
    protocols:
      http:
        endpoint: '[::1]:4318'

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

exporters:
  logging:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]

  telemetry:
    logs:
      level: "info"
  extensions: [memory_ballast]
