apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "registry-proxy.fullname" . }}-envoy
data:
  envoy.yaml: >
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 5000
        filter_chains:
        - filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: ingress_tcp
              cluster: docker-registry
              access_log:
              - name: envoy.file_access_log
                config:
                  path: "/dev/stdout"
              # Only allow connections from private network (source: https://en.wikipedia.org/wiki/Reserved_IP_addresses)
              source_ip_list:
              - 10.0.0.0/8
              - 100.64.0.0/10
              - 172.16.0.0/12
              - 192.168.0.0/16
              - 198.18.0.0/15
              # tracing:
              #   operation_name: egress
              # stat_prefix: ingress_http
      clusters:
      - name: docker-registry
        connect_timeout: 0.5s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: {{ .Values.registry.hostname }}
            port_value: 5000
    # tracing:
    #   http:
    #     name: envoy.zipkin
    #     config:
    #       collector_cluster: opentracing-proxy
    #       collector_endpoint: "/api/v1/spans"
