kind: Module
description: Postgres database for storing user names
type: helm
name: postgres
chart: stable/postgresql
version: 5.3.11
values:
  # This is a more digestable name than the default one in the template
  fullnameOverride: postgres
  # This should of course not be used in production
  postgresqlPassword: postgres
