apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-daemon.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "docker-daemon.name" . }}
    helm.sh/chart: {{ include "docker-daemon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "docker-daemon.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    # We only want one instance at a time, because we're using the same volume for the data
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "docker-daemon.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: garden-docker-data
          persistentVolumeClaim:
            claimName: garden-docker-data
        - name: garden-build-sync
          persistentVolumeClaim:
            claimName: {{ .Values.buildSync.volume.name }}
        - name: docker-config
          secret:
            secretName: builder-docker-config
            items:
              - key: .dockerconfigjson
                path: config.json
        {{- toYaml .Values.volumes | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: docker
              containerPort: 2376
              protocol: TCP
          securityContext:
            privileged: true
          readinessProbe:
            tcpSocket:
              port: 2376
            initialDelaySeconds: 10
            periodSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 2376
            initialDelaySeconds: 20
            periodSeconds: 20
          volumeMounts:
            - name: garden-docker-data
              mountPath: /var/lib/docker
            - name: garden-build-sync
              mountPath: /garden-build
            - name: docker-config
              mountPath: /root/.docker
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: proxy
          image: "gardendev/socat:0.1.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - TCP-LISTEN:5000,fork
            - TCP:{{ .Values.registry.hostname }}:5000
          ports:
            - name: proxy
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 5000
          readinessProbe:
            tcpSocket:
              port: 5000
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
