kind: Deploy
name: default-backend
description: Default backend ingress controller
type: container
spec:
# IMPORTANT: Please make sure to include the sha256 digest here
  image: gardendev/default-backend:v0.1@sha256:1b02920425eea569c6be53bb2e3d2c1182243212de229be375da7a93594498cf
  ports:
    - name: http
      containerPort: 80
