# Default values for skopeo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  name: gardendev/skopeo:1.41.0-3@sha256:082889982e35d7fda3b0ccd763312ceca21c0fce74b3e5e08c01081556e66533
  pullPolicy: IfNotPresent

nameOverride: "garden-util-daemon"
fullnameOverride: "garden-util-daemon"

resources:
  limits:
    cpu: "2"
    memory: "4Gi"
  requests:
    cpu: 200m
    memory: 256Mi

registry:
  hostname: garden-docker-registry

nodeSelector: {}

tolerations: []

affinity: {}
