name: Release the core npm package

on:
  release:
    types: [published]

jobs:
  publish-npm-package:
    runs-on: macOS-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build package
        run: |
          npm install
          npm build
      - name: Setup npm registry authentication
        working-directory: ./core
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
      - name: Publish edge version if pre-release
        if: github.event.release.prerelease == true
        working-directory: ./core
        # We fetch the current version from the package.json because at this point the version has
        # already been bumped during the pre-release process.
        run: |
          CURRENT_CORE_VERSION=`node -e "console.log(require('./package.json').version);"`
          npm version $CURRENT_CORE_VERSION-edge.$SHORT_SHA
          npm publish --tag edge
      - name: Publish stable version if normal release
        if: github.event.release.prerelease != true
        working-directory: ./core
        run: |
          npm publish
