name: Publish Garden release

on:
  release:
    # The workflow will run once the release has been published (i.e. is not in draft state anymore)
    # and it will only run if it is not a pre-release. See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
    types: [released]

permissions:
  contents: read

jobs:
  release-npm:
    runs-on: macos-latest
    steps:
      - name: Set Environment Variables
        run: echo "SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-8)" >> "$GITHUB_ENV"
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Use Node.js 20.x
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e
        with:
          node-version: 20.x
      - name: Build package
        run: |
          yarn
          yarn build
      - name: Setup npm registry authentication
        working-directory: ./core
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Publish edge version if pre-release
        if: github.event.release.prerelease == true
        working-directory: ./core
        run: |
          CURRENT_CORE_VERSION="$(node -e "console.log(require('./package.json').version);")"
          npm version "$CURRENT_CORE_VERSION-edge.$SHORT_SHA"
          npm publish --tag edge
      - name: Publish stable version if normal release
        if: github.event.release.prerelease != true
        working-directory: ./core
        run: |
          npm publish

  release-homebrew:
    uses: ./.github/workflows/reusable-create-homebrew-pr.yml
    with:
      release-condition: ${{ github.event.release.prerelease != true }}
      release-version: ${{ github.event.release.tag_name }}
      commit-message: |
        Bump {{formulaName}} to {{version}}.

        This PR has been generated by the publish-release workflow after the new release

        @${{ github.triggering_actor }} Please review this PR carefully and merge once Garden {{version}} should be released to Homebrew.
    secrets: inherit
