name: Reusable create homebrew PR
on:
  workflow_call:
    inputs:
      release-condition:
        type: string
        required: false
        description: "Example: false"
      release-version:
        type: string
        required: true
        description: "Example: 0.48.0"
      commit-message:
        type: string
        description: "Commit message for homebrew repository."
        default: |
          For more info: https://github.com/garden-io/garden

permissions:
  contents: read

jobs:
  homebrew-sha256:
    runs-on: ubuntu-latest
    env:
      MACOS_ARM_TARBALL_URL: https://download.garden.io/core/${{ inputs.release-version }}/garden-${{ inputs.release-version }}-macos-arm64.tar.gz
      MACOS_AMD_TARBALL_URL: https://download.garden.io/core/${{ inputs.release-version }}/garden-${{ inputs.release-version }}-macos-amd64.tar.gz
      LINUX_ARM_TARBALL_URL: https://download.garden.io/core/${{ inputs.release-version }}/garden-${{ inputs.release-version }}-linux-arm64.tar.gz
      LINUX_AMD_TARBALL_URL: https://download.garden.io/core/${{ inputs.release-version }}/garden-${{ inputs.release-version }}-linux-amd64.tar.gz
    outputs:
      macos-arm-tarball-url: ${{ env.MACOS_ARM_TARBALL_URL }}
      macos-amd-tarball-url: ${{ env.MACOS_AMD_TARBALL_URL }}
      macos-arm-sha256: ${{ steps.macos-arm.outputs.sha256 }}
      macos-amd-sha256: ${{ steps.macos-amd.outputs.sha256 }}
      linux-arm-tarball-url: ${{ env.LINUX_ARM_TARBALL_URL }}
      linux-amd-tarball-url: ${{ env.LINUX_AMD_TARBALL_URL }}
      linux-arm-sha256: ${{ steps.linux-arm.outputs.sha256 }}
      linux-amd-sha256: ${{ steps.linux-amd.outputs.sha256 }}
    steps:
      - name: Checkout garden repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # 4.0.0

      - name: Checksum Linux ARM64
        id: linux-arm
        uses: ./.github/actions/checksum
        with:
          url: ${{ env.LINUX_ARM_TARBALL_URL }}

      - name: Checksum Linux AMD64
        id: linux-amd
        uses: ./.github/actions/checksum
        with:
          url: ${{ env.LINUX_AMD_TARBALL_URL }}

      - name: Checksum MacOS ARM
        id: macos-arm
        uses: ./.github/actions/checksum
        with:
          url: ${{ env.MACOS_ARM_TARBALL_URL }}

      - name: Checksum MacOS AMD
        id: macos-amd
        uses: ./.github/actions/checksum
        with:
          url: ${{ env.MACOS_AMD_TARBALL_URL }}

  homebrew-create-pr:
    runs-on: ubuntu-latest
    needs: homebrew-sha256
    steps:
      - name: Checks release pre-condition
        if: inputs.release-condition == 'false'
        run: |
          echo The release-condition evaluated to false.
          echo Skipping all the next steps.

      - name: Checkout garden repo
        if: inputs.release-condition != 'false'
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # 4.0.0
        with:
          repository: garden-io/garden
          path: garden

      - name: Checkout homebrew repo
        if: inputs.release-condition != 'false'
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # 4.0.0
        with:
          repository: garden-io/homebrew-garden
          ref: main
          path: homebrew-garden
          token: ${{ secrets.COMMITTER_TOKEN }}

      - name: Template Homebrew Formula
        if: inputs.release-condition != 'false'
        uses: cuchi/jinja2-action@3fa06acb38601d3caea4c5ce0416e268a8799d71 # 1.2.1
        with:
          template: garden/support/homebrew-formula.rb.j2
          output_file: homebrew-garden/Formula/garden-cli.rb
          strict: true
          variables: |
            version=${{ inputs.release-version }}
            macosArmTarballUrl=${{ needs.homebrew-sha256.outputs.macos-arm-tarball-url }}
            macosAmdTarballUrl=${{ needs.homebrew-sha256.outputs.macos-amd-tarball-url }}
            macosArmSha256=${{ needs.homebrew-sha256.outputs.macos-arm-sha256 }}
            macosAmdSha256=${{ needs.homebrew-sha256.outputs.macos-amd-sha256 }}
            linuxArmTarballUrl=${{ needs.homebrew-sha256.outputs.linux-arm-tarball-url }}
            linuxAmdTarballUrl=${{ needs.homebrew-sha256.outputs.linux-amd-tarball-url }}
            linuxArmSha256=${{ needs.homebrew-sha256.outputs.linux-arm-sha256 }}
            linuxAmdSha256=${{ needs.homebrew-sha256.outputs.linux-amd-sha256 }}

      - name: Create PR on Homebrew Repository
        if: inputs.release-condition != 'false'
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # 5.0.2
        with:
          path: ${{ github.workspace }}/homebrew-garden
          token: ${{ secrets.COMMITTER_TOKEN }}
          commit-message: |
            Bump garden-cli.rb to ${{ inputs.release-version }}

            ${{ inputs.commit-message }}
          title: Bump garden-cli to ${{ inputs.release-version }}
          body:  |
            Bump garden-cli.rb to ${{ inputs.release-version }}

            ${{ inputs.commit-message}}
          branch: garden-cli-${{ inputs.release-version }}
          reviewers: ${{ github.triggering_actor }}

      - name: Adding markdown summary
        if: inputs.release-condition != 'false'
        run: |
          echo '### Manual Steps required to finish publishing to Homebrew' >> "$GITHUB_STEP_SUMMARY"
          echo 'Please review the new PR in https://github.com/garden-io/homebrew-garden/pulls' >> "$GITHUB_STEP_SUMMARY"
