name: Update Homebrew Formula

on:
  release:
    types: [published]

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  homebrew-release:
    runs-on: macos-latest

    steps:
      - name: Checks if pre-release
        if: github.event.release.prerelease == true
        run: |
          echo This is running against a pre-release.
          echo Skipping all the next steps.
      - name: Release Homebrew Formula
        if: github.event.release.prerelease != true
        uses: mislav/bump-homebrew-formula-action@a1aa5acee0698beefeac8f69f2eb8a5f292bf8bb
        with:
          formula-name: garden-cli
          formula-path: Formula/garden-cli.rb
          homebrew-tap: garden-io/homebrew-garden
          base-branch: main
          create-pullrequest: true
          download-url: https://download.garden.io/core/${{ github.event.release.tag_name }}/garden-${{ github.event.release.tag_name }}-macos-amd64.tar.gz
          commit-message: |
            Bump {{formulaName}} to {{version}}.

            For more info: https://github.com/garden-io/garden
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
      - name: Test Homebrew package
        if: github.event.release.prerelease != true
        run: |
          echo 'Testing brew install'
          brew tap garden-io/garden
          brew install garden-cli
          echo 'Running garden --version'
          garden --version
